# Generated by Django 4.0.6 on 2022-08-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rst_birthday_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hire_day',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
