# Generated by Django 4.0.6 on 2022-08-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rst_birthday_app', '0002_person_hire_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(default='работник', max_length=50),
            preserve_default=False,
        ),
    ]
