# Generated by Django 4.0.6 on 2022-08-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rst_birthday_app', '0003_person_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
