# Generated by Django 4.0.6 on 2022-08-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rst_birthday_app', '0004_person_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_position', models.CharField(default='Работник', max_length=64)),
                ('description_position', models.CharField(default='Работает', max_length=256)),
            ],
        ),
    ]
