# Generated by Django 4.0.6 on 2022-09-09 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rst_birthday_app', '0007_alter_person_first_name_alter_person_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='position',
        ),
        migrations.AddField(
            model_name='person',
            name='name_position',
            field=models.CharField(default='Работник', max_length=64),
        ),
        migrations.AlterField(
            model_name='position',
            name='name_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rst_birthday_app.person'),
        ),
    ]
